### ISSUE TITLE
hoisting

### ISSUE THREAD

**Issue by calvinmetcalf** [esnext/es6-class#8]
class declarations should be hoisted like functional declerations, meaning when you write

``` js
class Foo {

}
```

with this library you end up with something more equivalent to

``` js
var Foo = class {

}
```

**Comment by eventualbuddha** [comment]
This is definitely confusing, and could use clarification in the README. It does _seem_ like classes should hoist, since aren't class declarations just syntactic sugar for function declarations? No. The reason why is `extends`. For example:

``` js
class Animal {
}

class Dog extends Animal {
}
```

This seems fine. Even if you reverse the declaration order it still seems fine, if you assume both `Animal` and `Dog` are hoisted. However, the `extends` part of a class declaration is an expression, so this should be acceptable:

``` js
var Animal = function() {};

class Dog extends Animal {
}
```

If we were to hoist the declaration of `Dog` along with `Animal` our code would be incorrect:

``` js
var Animal;

class Dog extends Animal { // Animal is undefined!
}

Animal = function() {};
```

[This thread](http://esdiscuss.org/history/2014-06-05T15%3A54%3A16.000Z-rossberg.google.com?path=%2Ftopic%2Fin-es6-strict-mode-do-function-declarations-within-a-block-hoist) from es-discuss has a brief statement in support of this interpretation:

> In particular, classes don't "hoist", because their extends clause has to be evaluated at the right point in time.

I tried to find where this is spelled out in the spec and failed.

**Comment by calvinmetcalf** [comment]
wow that is confusing thanks

On Thu, Sep 4, 2014 at 12:40 PM, Brian Donovan notifications@github.com
wrote:

> This is definitely confusing, and could use clarification in the README.
> It does _seem_ like classes should hoist, since aren't class declarations
> just syntactic sugar for function declarations? No. The reason why is
> extends. For example:
> 
> class Animal {}
> class Dog extends Animal {}
> 
> This seems fine. Even if you reverse the declaration order it still seems
> fine, if you assume both Animal and Dog are hoisted. However, the extends
> part of a class declaration is an expression, so this should be acceptable:
> 
> var Animal = function() {};
> class Dog extends Animal {}
> 
> If we were to hoist the declaration of Dog along with Animal our code
> would be incorrect:
> 
> var Animal;
> class Dog extends Animal { // Animal is undefined!}
> Animal = function() {};
> 
> This thread
> http://esdiscuss.org/history/2014-06-05T15%3A54%3A16.000Z-rossberg.google.com?path=%2Ftopic%2Fin-es6-strict-mode-do-function-declarations-within-a-block-hoist
> from es-discuss has a brief statement in support of this interpretation:
> 
> In particular, classes don't "hoist", because their extends clause has to
> be evaluated at the right point in time.
> 
> I tried to find where this is spelled out in the spec and failed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/esnext/es6-class/issues/8#issuecomment-54507070.

## 

-Calvin W. Metcalf
